[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["backend/migrations"]

[tool.ruff.format]
quote-style = "single"

skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.ruff.lint.per-file-ignores]
"backend/app/api/**/*.py" = ["B008"]